import { Product } from "@/types/product_list_type";

export const products: Product[] = [
  // =========================
  // KHP Padlocks (matched to Lock_*. images)
  // =========================
  {
    id: "1",
    name: "15-R",
    price: 999,
    image: "/products/Lock_15-R.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Padlocks",
  },
  {
    id: "2",
    name: "Atoot 40mm",
    price: 799,
    image: "/products/Lock_Atoot40.jpeg",
    description: "To be Updated.",
    sizes: ["40mm"],
    category: "KHP Padlocks",
  },
  {
    id: "3",
    name: "Atoot 45mm",
    price: 849,
    image: "/products/Lock_Atoot45.jpeg",
    description: "To be Updated.",
    sizes: ["45mm"],
    category: "KHP Padlocks",
  },
  {
    id: "4",
    name: "Atoot 50mm",
    price: 899,
    image: "/products/Lock_Atoot50.jpeg",
    description: "To be Updated.",
    sizes: ["50mm"],
    category: "KHP Padlocks",
  },
  {
    id: "5",
    name: "Atoot 55mm",
    price: 0,
    image: "/products/Lock_Atoot55.png",
    description: "To be Updated.",
    sizes: ["55mm"],
    category: "KHP Padlocks",
  },
  {
    id: "6",
    name: "Atoot 60mm",
    price: 0,
    image: "/products/Lock_Atoot60.png",
    description: "To be Updated.",
    sizes: ["60mm"],
    category: "KHP Padlocks",
  },
  {
    id: "7",
    name: "Atoot 65mm",
    price: 0,
    image: "/products/Lock_Atoot65.png",
    description: "To be Updated.",
    sizes: ["65mm"],
    category: "KHP Padlocks",
  },
  {
    id: "8",
    name: "Atoot 70mm",
    price: 899,
    image: "/products/Lock_Atoot70.jpeg",
    description: "To be Updated.",
    sizes: ["70mm"],
    category: "KHP Padlocks",
  },
  {
    id: "9",
    name: "Super 35mm",
    price: 799,
    image: "/products/Lock_Super35.jpeg",
    description: "To be Updated.",
    sizes: ["35mm"],
    category: "KHP Padlocks",
  },
  {
    id: "10",
    name: "Super 50mm",
    price: 849,
    image: "/products/Lock_Super50.jpeg",
    description: "To be Updated.",
    sizes: ["50mm"],
    category: "KHP Padlocks",
  },
  {
    id: "11",
    name: "Super 60mm",
    price: 899,
    image: "/products/Lock_Super60.jpeg",
    description: "To be Updated.",
    sizes: ["60mm"],
    category: "KHP Padlocks",
  },
  {
    id: "12",
    name: "Super 65mm",
    price: 0,
    image: "/products/Lock_Super65.jpeg",
    description: "To be Updated.",
    sizes: ["65mm"],
    category: "KHP Padlocks",
  },
  {
    id: "13",
    name: "Classic 30mm",
    price: 0,
    image: "/products/Lock_Classic30.jpg",
    description: "To be Updated.",
    sizes: ["30mm"],
    category: "KHP Padlocks",
  },
  {
    id: "14",
    name: "Classic 40mm",
    price: 799,
    image: "/products/Lock_Classic40.jpeg",
    description: "To be Updated.",
    sizes: ["40mm"],
    category: "KHP Padlocks",
  },
  {
    id: "15",
    name: "Nexa",
    price: 899,
    image: "/products/Lock_Nexa.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Padlocks",
  },

  // =========================
  // KHP Cleaning Products
  // =========================
  {
    id: "16",
    name: "Cobweb Duster",
    price: 99,
    image: "/products/CobwebDuster.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Cleaning Products",
  },
  {
    id: "17",
    name: "Floor Wiper",
    price: 199,
    image: "/products/FloorWiper.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Cleaning Products",
  },
  {
    id: "18",
    name: "Microfiber Mop",
    price: 299,
    image: "/products/MicrofiberMop.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Cleaning Products",
  },

  // =========================
  // KHP Kitchen Cleaning Products (matched to Brite_*. images)
  // =========================
  {
    id: "19",
    name: "Non Scratch Scrubber",
    price: 49,
    image: "/products/Brite_NonScratchCleaner.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Kitchen Cleaning Products",
  },
  {
    id: "20",
    name: "Plastic Scrubber",
    price: 49,
    image: "/products/Brite_PScrubber.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Kitchen Cleaning Products",
  },
  {
    id: "21",
    name: "Scrubber",
    price: 49,
    image: "/products/Brite_Scrubber.png",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Kitchen Cleaning Products",
  },
  {
    id: "22",
    name: "Scrub Pad with Sponge",
    price: 49,
    image: "/products/Brite_ScrubPadwithSponge.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Kitchen Cleaning Products",
  },
  {
    id: "23",
    name: "Sponge Scrubber",
    price: 49,
    image: "/products/Brite_SpongeScrubber.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Kitchen Cleaning Products",
  },
  {
    id: "24",
    name: "Stainless Steel Scrubber",
    price: 49,
    image: "/products/Brite_StainlessSteelScrubber.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Kitchen Cleaning Products",
  },
];
