import { Product } from "@/types/product_list_type";

export const products: Product[] = [
  {
    id: "1",
    name: "15-R",
    price: 999,
    image: "/products/15-R.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Padlocks",
  },
  {
    id: "2",
    name: "Atoot 70mm",
    price: 899,
    image: "/products/Atoot70.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Padlocks",
  },
  {
    id: "3",
    name: "Cobweb Duster",
    price: 99,
    image: "/products/CobwebDuster.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Cleaning Products",
  },
  {
    id: "4",
    name: "No Scratch Scrubber",
    price: 49,
    image: "/products/NoScratchCleaner.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Kitchen Cleaning Products",
  },
  {
    id: "5",
    name: "Super 50mm",
    price: 849,
    image: "/products/Super50.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Padlocks",
  },
  {
    id: "6",
    name: "Atoot 40mm",
    price: 799,
    image: "/products/Atoot40.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Padlocks",
  },
  {
    id: "7",
    name: "Brite",
    price: 49,
    image: "/products/Brite.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Kitchen Cleaning Products",
  },
  {
    id: "8",
    name: "Floor Wiper",
    price: 199,
    image: "/products/FloorWiper.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Cleaning Products",
  },
  {
    id: "9",
    name: "Stainless Steel Scrubber",
    price: 49,
    image: "/products/Scrubber.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Kitchen Cleaning Products",
  },
  {
    id: "10",
    name: "Super 60mm",
    price: 899,
    image: "/products/Super60.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Padlocks",
  },
  {
    id: "11",
    name: "Atoot 45mm",
    price: 849,
    image: "/products/Atoot45.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Padlocks",
  },
  {
    id: "12",
    name: "Brite (Sponge)",
    price: 49,
    image: "/products/BriteSponge.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Kitchen Cleaning Products",
  },
  {
    id: "13",
    name: "Microfiber Mop",
    price: 299,
    image: "/products/MicrofiberMop.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Cleaning Products",
  },
  {
    id: "14",
    name: "Super 35mm",
    price: 799,
    image: "/products/Super35.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Padlocks",
  },
  {
    id: "15",
    name: "Atoot 50mm",
    price: 899,
    image: "/products/Atoot50.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Padlocks",
  },
  {
    id: "16",
    name: "Classic",
    price: 799,
    image: "/products/Classic.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Padlocks",
  },
  {
    id: "17",
    name: "Nexa",
    price: 899,
    image: "/products/Nexa.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Padlocks",
  },
  {
    id: "18",
    name: "Super 40mm",
    price: 49,
    image: "/products/Super40.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Padlocks",
  },
  {
    id: "19",
    name: "Super 65mm",
    price: 49,
    image: "/products/Super65.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Padlocks",
  }
];