// components/product_list.ts

import { Product } from "@/types/product_list_type";

export const products: Product[] = [
  {
    id: "1",
    name: "15-R",
    price: 999,
    image: "/products/15-R.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Padlocks",
  },
  {
    id: "2",
    name: "Atoot",
    price: 899,
    image: "/products/Atoot.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Padlocks",
  },
  {
    id: "3",
    name: "Classic",
    price: 799,
    image: "/products/Classic.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Padlocks",
  },
  {
    id: "4",
    name: "Nexa",
    price: 899,
    image: "/products/Nexa.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Padlocks",
  },
  {
    id: "5",
    name: "Super 35mm",
    price: 799,
    image: "/products/Super35.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Padlocks",
  },
  {
    id: "6",
    name: "Super 50mm",
    price: 849,
    image: "/products/Super50.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Padlocks",
  },
  {
    id: "7",
    name: "Super 60mm",
    price: 899,
    image: "/products/Super60.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Padlocks",
  },
  {
    id: "8",
    name: "MS Scrubber",
    price: 49,
    image: "/products/Brite.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Kitchen Cleaning Products",
  },
  {
    id: "9",
    name: "Stainless Steel Scrubber",
    price: 49,
    image: "/products/Scrubber.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Kitchen Cleaning Products",
  },
  {
    id: "10",
    name: "Super 40mm",
    price: 49,
    image: "/products/Super40.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Padlocks",
  },
  {
    id: "11",
    name: "No Scratch Scrubber",
    price: 49,
    image: "/products/NoScratchCleaner.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Kitchen Cleaning Products",
  },
  {
    id: "12",
    name: "Brite (Sponge)",
    price: 49,
    image: "/products/BriteSponge.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Kitchen Cleaning Products",
  },
  {
    id: "13",
    name: "Super 65mm",
    price: 49,
    image: "/products/Super65.jpeg",
    description: "To be Updated.",
    sizes: ["To Be Updated"],
    category: "KHP Padlocks",
  }
];